app:
  postgres:
    datasource:
      jdbc-url: jdbc:postgresql://localhost:5432/mytest
      username: postgres
      password: password
      pool-size: 10
spring:
  flyway:
    baseline-on-migrate: true
