app:
  postgres:
    datasource:
      jdbc-url: jdbc:postgresql://localhost:5432/mytest
      username: postgres
      password: password
      pool-size: 10
flyway:
  baseline-on-migrate: true
  baseline-version: 0
spring:
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
  session:
    store-type: none
