app:
  postgres:
    datasource:
      jdbc-url: jdbc:postgresql://localhost:5432/mytest
      username: postgres
      password: password
      pool-size: 10
flyway:
  baseline-on-migrate: true
  baseline-version: 0
spring:
  h2:
    console:
      path: /h2
      enabled: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    #url: jdbc:h2:file:./
    username: sa
    password:

  flyway:
    baseline-on-migrate: true
    baseline-version: 0
  jpa:
    defer-datasource-initialization: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
      # ddl-auto: create-drop
      #naming:
        #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    session:
      store-type: none
    datasource:
      # driver-class-name: org.hsqldb.jdbc.JDBCDriver
      # url: jdbc:hsqldb:mem:test;DB_CLOSE_DELAY=-1
      data: classpath:db/data.sql
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
      #url: jdbc:h2:file:./
      username: sa
      password:
